
namespace :dev do
  desc "Build system"
  task :build   => ["tmp:clear", "log:clear", "db:drop", "db:create", "db:migrate"]

  desc "Rebuild system with seeds"
  task :rebuild => ["dev:build", "db:seed"]

  desc "Generate fake data"
  task :fake => :environment do
    # create some test users
    4.times do |i|
      user = User.create(
        :email => "bruce+#{i}@gmail.com.tw",
        :password => "abcd1234",
        :password_confirmation => "abcd1234"
      )
    end

    # including admin account (which generated by seeds)
    user_ids = User.limit(5).pluck(:id)

    fake_board_names = [
      "Music", "Games", "Auto", "Animation", "Comics", "Novel",
      "Readin", "PC", "Mac", "iPhone", "Tech", "Beauty", "Cooking", "Joke"
    ].shuffle

    # creating test boards and posts
    fake_board_names.each do |fake_board_name|
      board = Board.create(:name => fake_board_name)
      rand(1..20).times do |k|
        post = board.posts.build(generate_fake_post_attributes)
        post.user_id = user_ids.shuffle.first
        post.save!
      end
    end
  end

  private

  def generate_fake_post_attributes
    lorem_ipsum = <<-LOREM
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
deserunt mollit anim id est laborum.
LOREM

    {
      :title   => lorem_ipsum.split.shuffle.first(5).join(" "),
      :content => lorem_ipsum
    }
  end
end
