
namespace :dev do
  desc "Build system"
  task :build   => ["tmp:clear", "log:clear", "db:drop", "db:create", "db:migrate"]

  desc "Rebuild system with seeds"
  task :rebuild => ["dev:build", "db:seed"]

  desc "Generate fake data"
  task :fake => :environment do
    # create some test users
    4.times.each do |i|
      user = User.new(
        :email => "bruce+#{i}@gmail.com.tw",
        :password => "abcd1234",
        :password_confirmation => "abcd1234"
      )
      user.save
    end

    # including admin account (which generated by seeds)
    user_ids = User.limit(5).map {|user| user.id }

    fake_board_names = ["Music", "Games", "Auto", "Animation", "Comics", "Novel",
      "Readin", "PC", "Mac", "iPhone", "Tech", "Beauty", "Cooking", "Joke"].shuffle

    # creating test boards and posts
    fake_board_names.each do |fake_board_name|
      board = Board.create(:name => fake_board_name)
      rand(1..20).times.each do |k|
        post = board.posts.build(fake_post)
        post.user_id = user_ids.shuffle.first
        post.save!
      end
    end
  end

  private

  def fake_post
    lorem_ipsum = %{Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.}
    {
      :title   => lorem_ipsum.split.shuffle.first(5).join(" "),
      :content => lorem_ipsum
    }
  end
end
